export default {
  api: {
    medals: 'http://olympics.atelerix.co/medals',
    medalList: 'http://wowappprd.rio2016.com/json/medals/OG2016_medalsList.json',
    countryMedals: 'http://wowappprd.rio2016.com/countries/countriesMedals?lang_code=ENG&os_kind=ANDROID&competition_code=OG2016&noc_code=',
    countryInfo: 'https://wamsgtpenv.rio2016.com/v1/en/olympic/country/'
  },
  sports: {
    AR: 'Archery',
    AT: 'Athletics',
    WR: 'Wrestling',
    WP: 'Water Polo',
    WL: 'Weightlifting',
    VO: 'Volleyball',
    TT: 'Table Tennis',
    TR: 'Triathlon',
    TK: 'Taekwondo',
    TE: 'Tennis',
    SY: 'Synchronised Swimming',
    SW: 'Swimming',
    SH: 'Shooting',
    SA: 'Sailing',
    RU: 'Rugby Sevens',
    RO: 'Rowing',
    OW: 'Marathon Swimming',
    MP: 'Modern Pentathlon',
    JU: 'Judo',
    HO: 'Hockey',
    HB: 'Handball',
    GT: 'Trampoline Gymnastics',
    GR: 'Rhythmic Gymnastics',
    GO: 'Golf',
    BD: 'Badminton',
    BK: 'Basketball',
    BV: 'Beach Volleyball',
    BX: 'Boxing',
    CB: 'Cycling BMX',
    CF: 'Canoe Sprint',
    CM: 'Cycling Mountain Bike',
    CR: 'Cycling Road',
    CS: 'Canoe Slalom',
    CT: 'Cycling Track',
    DV: 'Diving',
    EQ: 'Equestrian',
    FB: 'Football',
    FE: 'Fencing',
    GA: 'Artistic Gymnastics'
  },
  countryCodes: {
    ROT: 'Refugee Olympic Team',
    ROA: 'Refugee Olympic Athlete',
    SSD: 'South Sudan',
    IOP: 'Independent Olympic Participant',
    THA: 'Thailand',
    NOR: 'Norway',
    NRU: 'Nauru',
    NZL: 'New Zealand',
    OMA: 'Oman',
    PAK: 'Pakistan',
    PAN: 'Panama',
    PAR: 'Paraguay',
    PER: 'Peru',
    PHI: 'Philippines',
    PLE: 'Palestine',
    PLW: 'Palau',
    PNG: 'Papua New Guinea',
    POL: 'Poland',
    POR: 'Portugal',
    PRK: 'Democratic People\'s Republic of Korea',
    PUR: 'Puerto Rico',
    QAT: 'Qatar',
    ROU: 'Romania',
    RUS: 'Russian Federation',
    RWA: 'Rwanda',
    SAM: 'Samoa',
    SCG: 'Serbia and Montenegro',
    SEN: 'Senegal',
    SIN: 'Singapore',
    SKN: 'Saint Kitts and Nevis',
    SLE: 'Sierra Leone',
    SMR: 'San Marino',
    SOL: 'Solomon Islands',
    SOM: 'Somalia',
    SRB: 'Serbia',
    SRI: 'Sri Lanka',
    SUD: 'Sudan',
    SUI: 'Switzerland',
    SUR: 'Suriname',
    SVK: 'Slovakia',
    SWE: 'Sweden',
    SWZ: 'Swaziland',
    SYR: 'Syrian Arab Republic',
    TAH: 'Tahiti',
    TAN: 'United Republic of Tanzania',
    TCH: 'Czechoslovakia',
    TGA: 'Tonga',
    CIS: 'Commonwealth of Independent States',
    CRC: 'Costa Rica',
    DMA: 'Dominica',
    JAM: 'Jamaica',
    KIR: 'Kiribati',
    KUW: 'Kuwait',
    LCA: 'Saint Lucia',
    MAD: 'Madagascar',
    RSA: 'South Africa',
    SEY: 'Seychelles',
    SLO: 'Slovenia',
    STP: 'Sao Tome and Principe',
    TUR: 'Turkey',
    URS: 'USSR',
    VEN: 'Venezuela',
    YUG: 'The Federal Republic of Yugoslavia',
    TJK: 'Tajikistan',
    TKM: 'Turkmenistan',
    TLS: 'Democratic Republic of Timor-Leste',
    TOG: 'Togo',
    TPE: 'Chinese Taipei',
    TTO: 'Trinidad and Tobago',
    TUN: 'Tunisia',
    TUV: 'Tuvalu',
    UAE: 'United Arab Emirates',
    UGA: 'Uganda',
    UKR: 'Ukraine',
    URU: 'Uruguay',
    USA: 'United States of America',
    UZB: 'Uzbekistan',
    VAN: 'Vanuatu',
    VIE: 'Vietnam',
    VIN: 'St Vincent and the Grenadines',
    YEM: 'Yemen',
    ZAM: 'Zambia',
    ZIM: 'Zimbabwe',
    AFG: 'Afghanistan',
    AHO: 'Netherlands Antilles',
    ALB: 'Albania',
    ALG: 'Algeria',
    AND: 'Andorra',
    ANG: 'Angola',
    ANT: 'Antigua and Barbuda',
    ANZ: 'Australia/New Zealand',
    ARG: 'Argentina',
    ARM: 'Armenia',
    ARU: 'Aruba',
    ASA: 'American Samoa',
    AUS: 'Australia',
    AUT: 'Austria',
    AZE: 'Azerbaijan',
    BAH: 'Bahamas',
    BAN: 'Bangladesh',
    BAR: 'Barbados',
    BDI: 'Burundi',
    BEL: 'Belgium',
    BEN: 'Benin',
    BER: 'Bermuda',
    BHU: 'Bhutan',
    BIH: 'Bosnia and Herzegovina',
    BIZ: 'Belize',
    BLR: 'Belarus',
    BOL: 'Bolivia',
    BOT: 'Botswana',
    BRA: 'Brazil',
    BRN: 'Bahrain',
    BRU: 'Brunei Darussalam',
    BUL: 'Bulgaria',
    BUR: 'Burkina Faso',
    CAF: 'Central African Republic',
    CAM: 'Cambodia',
    CAN: 'Canada',
    CAY: 'Cayman Islands',
    CGO: 'Congo',
    CHA: 'Chad',
    CHI: 'Chile',
    CHN: 'People\'s Republic of China',
    CIV: 'Côte d\'Ivoire',
    CMR: 'Cameroon',
    COD: 'Democratic Republic of the Congo',
    COK: 'Cook Islands',
    COL: 'Colombia',
    COM: 'Comoros',
    CPV: 'Cape Verde',
    CRO: 'Croatia',
    CUB: 'Cuba',
    CYP: 'Cyprus',
    CZE: 'Czech Republic',
    DEN: 'Denmark',
    DJI: 'Djibouti',
    DOM: 'Dominican Republic',
    ECU: 'Ecuador',
    EGY: 'Egypt',
    ENG: 'England',
    ERI: 'Eritrea',
    ESA: 'El Salvador',
    ESP: 'Spain',
    EST: 'Estonia',
    ETH: 'Ethiopia',
    EUN: 'Unified Team',
    FIJ: 'Fiji',
    FIN: 'Finland',
    FRA: 'France',
    FRG: 'Federal Republic of Germany',
    FSM: 'Federated States of Micronesia',
    GAB: 'Gabon',
    GAM: 'Gambia',
    GBR: 'Great Britain',
    GBS: 'Guinea-Bissau',
    GDR: 'GDR',
    GEO: 'Georgia',
    GEQ: 'Equatorial Guinea',
    GER: 'Germany',
    GHA: 'Ghana',
    GRE: 'Greece',
    GRN: 'Grenada',
    GUA: 'Guatemala',
    GUI: 'Guinea',
    GUM: 'Guam',
    GUY: 'Guyana',
    HAI: 'Haiti',
    HKG: 'Hong Kong, China',
    HON: 'Honduras',
    HUN: 'Hungary',
    INA: 'Indonesia',
    IND: 'India',
    IOA: 'Independent Olympic Athlete',
    IRI: 'Islamic Republic of Iran',
    IRL: 'Ireland',
    IRQ: 'Iraq',
    ISL: 'Iceland',
    ISR: 'Israel',
    ISV: 'Virgin Islands, US',
    ITA: 'Italy',
    IVB: 'Virgin Islands, British',
    JOR: 'Jordan',
    JPN: 'Japan',
    KAZ: 'Kazakhstan',
    KEN: 'Kenya',
    KGZ: 'Kyrgyzstan',
    KOR: 'Republic of Korea',
    KOS: 'Kosovo',
    KSA: 'Saudi Arabia',
    LAO: 'Lao People\'s Democratic Republic',
    LAT: 'Latvia',
    LBA: 'Libya',
    LBR: 'Liberia',
    LES: 'Lesotho',
    LIB: 'Lebanon',
    LIE: 'Liechtenstein',
    LTU: 'Lithuania',
    LUX: 'Luxembourg',
    MAR: 'Morocco',
    MAS: 'Malaysia',
    MAW: 'Malawi',
    MDA: 'Republic of Moldova',
    MDV: 'Maldives',
    MEX: 'Mexico',
    MGL: 'Mongolia',
    MHL: 'Marshall Islands',
    MKD: 'The Former Yugoslav Republic of Macedonia',
    MLI: 'Mali',
    MLT: 'Malta',
    MNE: 'Montenegro',
    MON: 'Monaco',
    MOZ: 'Mozambique',
    MRI: 'Mauritius',
    MTN: 'Mauritania',
    MYA: 'Myanmar',
    NAM: 'Namibia',
    NCA: 'Nicaragua',
    NED: 'Netherlands',
    NEP: 'Nepal',
    NGR: 'Nigeria',
    NIG: 'Niger'
  },
  countryNames: {
    "refugee olympic team": "ROT",
    "refugee olympic athlete": "ROA",
    "south sudan": "SSD",
    "independent olympic participant": "IOP",
    "thailand": "THA",
    "norway": "NOR",
    "nauru": "NRU",
    "new zealand": "NZL",
    "oman": "OMA",
    "pakistan": "PAK",
    "panama": "PAN",
    "paraguay": "PAR",
    "peru": "PER",
    "philippines": "PHI",
    "palestine": "PLE",
    "palau": "PLW",
    "papua new guinea": "PNG",
    "poland": "POL",
    "portugal": "POR",
    "democratic people's republic of korea": "PRK",
    "puerto rico": "PUR",
    "qatar": "QAT",
    "romania": "ROU",
    "russian federation": "RUS",
    "rwanda": "RWA",
    "samoa": "SAM",
    "serbia and montenegro": "SCG",
    "senegal": "SEN",
    "singapore": "SIN",
    "saint kitts and nevis": "SKN",
    "sierra leone": "SLE",
    "san marino": "SMR",
    "solomon islands": "SOL",
    "somalia": "SOM",
    "serbia": "SRB",
    "sri lanka": "SRI",
    "sudan": "SUD",
    "switzerland": "SUI",
    "suriname": "SUR",
    "slovakia": "SVK",
    "sweden": "SWE",
    "swaziland": "SWZ",
    "syrian arab republic": "SYR",
    "tahiti": "TAH",
    "united republic of tanzania": "TAN",
    "czechoslovakia": "TCH",
    "tonga": "TGA",
    "commonwealth of independent states": "CIS",
    "costa rica": "CRC",
    "dominica": "DMA",
    "jamaica": "JAM",
    "kiribati": "KIR",
    "kuwait": "KUW",
    "saint lucia": "LCA",
    "madagascar": "MAD",
    "south africa": "RSA",
    "seychelles": "SEY",
    "slovenia": "SLO",
    "sao tome and principe": "STP",
    "turkey": "TUR",
    "ussr": "URS",
    "venezuela": "VEN",
    "the federal republic of yugoslavia": "YUG",
    "tajikistan": "TJK",
    "turkmenistan": "TKM",
    "democratic republic of timor-leste": "TLS",
    "togo": "TOG",
    "chinese taipei": "TPE",
    "trinidad and tobago": "TTO",
    "tunisia": "TUN",
    "tuvalu": "TUV",
    "united arab emirates": "UAE",
    "uganda": "UGA",
    "ukraine": "UKR",
    "uruguay": "URU",
    "united states of america": "USA",
    "uzbekistan": "UZB",
    "vanuatu": "VAN",
    "vietnam": "VIE",
    "st vincent and the grenadines": "VIN",
    "yemen": "YEM",
    "zambia": "ZAM",
    "zimbabwe": "ZIM",
    "afghanistan": "AFG",
    "netherlands antilles": "AHO",
    "albania": "ALB",
    "algeria": "ALG",
    "andorra": "AND",
    "angola": "ANG",
    "antigua and barbuda": "ANT",
    "australia/new zealand": "ANZ",
    "argentina": "ARG",
    "armenia": "ARM",
    "aruba": "ARU",
    "american samoa": "ASA",
    "australia": "AUS",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahamas": "BAH",
    "bangladesh": "BAN",
    "barbados": "BAR",
    "burundi": "BDI",
    "belgium": "BEL",
    "benin": "BEN",
    "bermuda": "BER",
    "bhutan": "BHU",
    "bosnia and herzegovina": "BIH",
    "belize": "BIZ",
    "belarus": "BLR",
    "bolivia": "BOL",
    "botswana": "BOT",
    "brazil": "BRA",
    "bahrain": "BRN",
    "brunei darussalam": "BRU",
    "bulgaria": "BUL",
    "burkina faso": "BUR",
    "central african republic": "CAF",
    "cambodia": "CAM",
    "canada": "CAN",
    "cayman islands": "CAY",
    "congo": "CGO",
    "chad": "CHA",
    "chile": "CHI",
    "people's republic of china": "CHN",
    "côte d'ivoire": "CIV",
    "cameroon": "CMR",
    "democratic republic of the congo": "COD",
    "cook islands": "COK",
    "colombia": "COL",
    "comoros": "COM",
    "cape verde": "CPV",
    "croatia": "CRO",
    "cuba": "CUB",
    "cyprus": "CYP",
    "czech republic": "CZE",
    "denmark": "DEN",
    "djibouti": "DJI",
    "dominican republic": "DOM",
    "ecuador": "ECU",
    "egypt": "EGY",
    "england": "ENG",
    "eritrea": "ERI",
    "el salvador": "ESA",
    "spain": "ESP",
    "estonia": "EST",
    "ethiopia": "ETH",
    "unified team": "EUN",
    "fiji": "FIJ",
    "finland": "FIN",
    "france": "FRA",
    "federal republic of germany": "FRG",
    "federated states of micronesia": "FSM",
    "gabon": "GAB",
    "gambia": "GAM",
    "great britain": "GBR",
    "guinea-bissau": "GBS",
    "gdr": "GDR",
    "georgia": "GEO",
    "equatorial guinea": "GEQ",
    "germany": "GER",
    "ghana": "GHA",
    "greece": "GRE",
    "grenada": "GRN",
    "guatemala": "GUA",
    "guinea": "GUI",
    "guam": "GUM",
    "guyana": "GUY",
    "haiti": "HAI",
    "hong kong, china": "HKG",
    "honduras": "HON",
    "hungary": "HUN",
    "indonesia": "INA",
    "india": "IND",
    "independent olympic athlete": "IOA",
    "islamic republic of iran": "IRI",
    "ireland": "IRL",
    "iraq": "IRQ",
    "iceland": "ISL",
    "israel": "ISR",
    "virgin islands, us": "ISV",
    "italy": "ITA",
    "virgin islands, british": "IVB",
    "jordan": "JOR",
    "japan": "JPN",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "kyrgyzstan": "KGZ",
    "republic of korea": "KOR",
    "kosovo": "KOS",
    "saudi arabia": "KSA",
    "lao people's democratic republic": "LAO",
    "latvia": "LAT",
    "libya": "LBA",
    "liberia": "LBR",
    "lesotho": "LES",
    "lebanon": "LIB",
    "liechtenstein": "LIE",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "morocco": "MAR",
    "malaysia": "MAS",
    "malawi": "MAW",
    "republic of moldova": "MDA",
    "maldives": "MDV",
    "mexico": "MEX",
    "mongolia": "MGL",
    "marshall islands": "MHL",
    "the former yugoslav republic of macedonia": "MKD",
    "mali": "MLI",
    "malta": "MLT",
    "montenegro": "MNE",
    "monaco": "MON",
    "mozambique": "MOZ",
    "mauritius": "MRI",
    "mauritania": "MTN",
    "myanmar": "MYA",
    "namibia": "NAM",
    "nicaragua": "NCA",
    "netherlands": "NED",
    "nepal": "NEP",
    "nigeria": "NGR",
    "niger": "NIG"
  }
}
