export default {
  statusCodes: {
    // nginx Codes
    "444": "No Response",
    "495": "SSL Certificate Error",
    "496": "SSL Certificate Required",
    "497": "HTTP Request Sent to HTTPS Port",
    "499": "Client Closed Request",

    // Cloudflare Codes
    "520": "Unknown Error",
    "521": "Web Server Is Down",
    "522": "Connection Timed Out",
    "523": "Origin Is Unreachable",
    "524": "A Timeout Occurred",
    "525": "SSL Handshake Failed",
    "526": "Invalid SSL Certificate",
    "527": "Railgun Error",

    // Memes
    "701": "Meh",
    "702": "Emacs",
    "703": "Explosion",
    "704": "Goto Fail",
    "705": "I wrote the code and missed the necessary validation by an oversight (see 795)",
    "706": "Delete Your Account",
    "707": "Can't quit vi",
    "710": "PHP",
    "711": "Convenience Store",
    "712": "NoSQL",
    "718": "I am not a teapot",
    "719": "Haskell",
    "720": "Unpossible",
    "721": "Known Unknowns",
    "722": "Unknown Unknowns",
    "723": "Tricky",
    "724": "This line should be unreachable",
    "725": "It works on my machine",
    "726": "It's a feature, not a bug",
    "727": "32 bits is plenty",
    "728": "Go Fish",
    "730": "Fucking Bower",
    "731": "Fucking Rubygems",
    "732": "Fucking Unic💩de",
    "733": "Fucking Deadlocks",
    "734": "Fucking Deferreds",
    "735": "Fucking IE",
    "736": "Fucking Race Conditions",
    "737": "FuckThreadsing",
    "738": "Fucking Bundler",
    "739": "Fucking Windows",
    "740": "Computer says no",
    "741": "Compiling",
    "742": "A kitten dies",
    "743": "I thought I knew regular expressions",
    "744": "Y U NO write integration tests?",
    "745": "I don't always test my code, but when I do I do it in production",
    "746": "Missed Ballmer Peak",
    "747": "Motherfucking Snakes on the Motherfucking Plane",
    "748": "Confounded by Ponies",
    "749": "Reserved for Chuck Norris",
    "750": "Didn't bother to compile it",
    "753": "Syntax Error",
    "754": "Too many semi",
    "755": "Not enough semi",
    "756": "Insufficiently polite",
    "757": "Excessively polite",
    "759": "Unexpected T_PAAMAYIM_NEKUDOTAYIM",
    "761": "Hungover",
    "762": "Stoned",
    "763": "Under",
    "764": "Over",
    "765": "Railscamp",
    "766": "Sober",
    "767": "Drunk",
    "768": "Accidentally Took Sleeping Pills Instead Of Migraine Pills During Crunch Week",
    "769": "Questionable Maturity Level",
    "771": "Cached for too long",
    "772": "Not cached long enough",
    "773": "Not cached at all",
    "774": "Why was this cached?",
    "775": "Out of cash",
    "776": "Error on the Exception",
    "777": "Coincidence",
    "778": "Off By One Error",
    "779": "Off By Too Many To Count Error",
    "780": "Project owner not responding",
    "781": "Operations",
    "782": "QA",
    "783": "It was a customer request, honestly",
    "784": "Management, obviously",
    "785": "TPS Cover Sheet not attached",
    "786": "Try it now",
    "787": "Further Funding Required",
    "788": "Designer's final designs weren't",
    "789": "Not my department",
    "791": "The Internet shut down due to copyright restrictions",
    "792": "Climate change driven catastrophic weather event",
    "793": "Zombie Apocalypse",
    "794": "Someone let PG near a REPL",
    "795": "#heartbleed (see 705)",
    "797": "This is the last page of the Internet. Go back",
    "799": "End of the world"
  },
  clap: {
    sincere: ["http://i.imgur.com/pfrtv6H.gif", "http://i.imgur.com/Bp4P8l3.gif", "http://i.imgur.com/v7mZ22P.gif", "http://i.imgur.com/S1v4KuY.gif", "http://i.imgur.com/YTaSAkq.gif", "http://i.imgur.com/JO6Wz3r.gif", "http://i.imgur.com/pWEd6cF.gif", "http://i.imgur.com/zumSlIA.gif", "http://i.imgur.com/RGczKmV.gif", "http://i.imgur.com/KAQhoCm.gif", "http://i.imgur.com/PASRKXo.gif", "http://i.imgur.com/ZOWQTO6.gif", "http://i.imgur.com/cY0eH5c.gif", "http://i.imgur.com/wf5qvOM.gif", "http://i.imgur.com/9Zv4V.gif", "http://i.imgur.com/t8zvc.gif", "http://cache.blippitt.com/wp-content/uploads/2012/06/Daily-Life-GIFs-06-The-Rock-Clapping.gif", "http://25.media.tumblr.com/tumblr_m00e9mCyWj1rqtbn0o1_500.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/Kurtclapping.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/riker.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/hp3.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/1292223254212-dumpfm-mario-Obamaclap.gif", "http://www.reactiongifs.com/wp-content/uploads/2013/01/applause.gif", "http://stream1.gifsoup.com/view7/4263859/billy-madison-clapping-o.gif"],
    insincere: ["http://i.imgur.com/2QXgcqP.gif", "http://i.imgur.com/Yih2Lcg.gif", "http://i.imgur.com/un3MuET.gif", "http://i.imgur.com/H2wPc1d.gif", "http://i.imgur.com/uOtALBE.gif", "http://i.imgur.com/nmqrdiF.gif", "http://i.imgur.com/GgxOUGt.gif", "http://i.imgur.com/wyTQMD6.gif", "http://i.imgur.com/GYRGOy6.gif", "http://i.imgur.com/ojIsLUA.gif", "http://i.imgur.com/bRetADl.gif", "http://i.imgur.com/814mkEC.gif", "http://i.imgur.com/uYryMyr.gif", "http://i.imgur.com/YfrikPR.gif", "http://i.imgur.com/sBEFqYR.gif", "http://i.imgur.com/Sx8iAS8.gif", "http://i.imgur.com/5zKXz.gif"]
  },
  flirts: [
    "covers %s in blancmange",
    "jumps for joy at the thought of %s",
    "offers %s a bunch of flowers",
    "blows kisses at %s",
    "falls head over heels in love with %s",
    "offers to take %s out for dinner",
    "is %s's kind of robot",
    "offers %s a Turkish Delight",
    "gazes contentedly at %s",
    "offers %s a cherry",
    "imagines %s in a tutu",
    "catches %s's eye across a crowded room",
    "kisses %s's hand",
    "wonders what a nice person like %s is doing in a place like this",
    "licks chocolate sauce off %s",
    "gets down on one knee in front of %s",
    "bats its eyelashes at %s",
    "winks suggestively at %s",
    "blabbers incoherently at the sight of %s",
    "mentally undresses %s",
    "daydreams about %s",
    "wonders what %s is really thinking",
    "gazes mutely into %s's eyes",
    "wonders if %s might reciprocate its feelings",
    "whispers sweet nothings to %s",
    "sends %s a red rose",
    "toasts %s with champagne",
    "offers %s its last Rolo",
    "invites %s up for coffee",
    "promises %s a night to remember",
    "invites %s in to see its etchings",
    "wonders if %s is really that innocent",
    "serenades %s",
    "puts a rose between its teeth and tangoes seductively with %s",
    "plays with its hair whilst gazing at %s",
    "draws a magic circle around itself and %s",
    "tickles %s playfully",
    "draws a flattering portrait of %s",
    "poings happily at the sight of %s",
    "gives %s a high-five",
    "brushes lint off %s's clothing",
    "dims the lights for %s",
    "invites %s behind the bike sheds",
    "rides a tightrope on a unicycle while juggling chainsaws in an attempt to impress %s",
    "composes haiku for %s",
    "makes the tea for %s",
    "sprinkles %s with hundreds and thousands",
    "flagellates %s with a birch branch",
    "<3s %s",
    "admires %s's boots",
    "invites %s to a candle-lit dinner",
    "hopes %s packed their toothbrush!",
    "showers %s in rose petals",
    "holds a candle for %s",
    "admires %s's physique",
    "gives %s a nice relaxing foot massage",
    "treks through the jungle to deliver Milk Tray to %s",
    "searches for a rhyme for its poem about %s",
    "compares %s's eyes to stars",
    "wonders whether %s comes here often?",
    "compares %s to a summer's day",
    "curls up at %s's feet",
    "plays %s's theme tune",
    "sends for %s and more golden syrup",
    "puts %s on top of the Christmas tree",
    "writes flirts just for %s",
    "thinks %s is the new hotness",
    "imagines %s in a sailor outfit",
    "would like to cause earthquakes with %s",
    "creates an \" I bet we can get a million people who fancy % s \" group on Facebook",
    "becomes a fan of %s",
    "turns down the house lights for %s",
    "invites %s up to see its iPad",
    "can't wait to unbox %s",
    "blows %s's vuvuzela",
    "wonders if %s is multi-touch",
    "tips its hat to %s",
    "would Photoshop %s but they are perfect already",
    "would betray its country for %s",
    "creates a dozen extra Twitter accounts just to follow %s",
    "wears sexy underwear just for %s",
    "is never gonna give %s up",
    "wants to FaceTime %s",
    "spies on %s through their webcam",
    "dyes its hair for %s",
    "newgroups alt.fan.%s",
    "tattoos %s's name on its bottom",
    "makes a backup copy of %s",
    "throws itself at %s's feet",
    "buys %s a nice dress",
    "buys %s a revealing dress",
    "asks %s out on a date",
    "posts pictures of %s to rule34.paheal.net [NWS!]",
    "emails %s its favourite cat pictures",
    "lends %s all its spoons",
    "searches the internet for pictures of %s",
    "writes to Dan Savage for tips on seducing %s",
    "cross-dresses just for %s",
    "buys a telephoto lens just to take pictures of %s",
    "offers %s some Madeira",
    "offers %s a fork",
    "gives %s a thumbs-up",
    "goes speed-dating with a dozen clones of %s",
    "writes a webcomic about the adventures of %s",
    "dresses up as Batman for %s",
    "club mammoth for %s. Ug!",
    "sexts %s",
    "defeats all of %s's evil exes",
    "clones %s's repo",
    "thinks %s is cuter than all the My Little Ponies put together",
    "would open the pod bay doors for %s",
    "takes upskirt photos of %s",
    "sniffs %s's underwear",
    "writes thousands of lines of elisp just for %s",
    "showers %s with porcelain sunflower seeds",
    "creates a .xxx domain just for %s",
    "hopes rule 34 applies to %s",
    "unzips %s",
    "drives its tractor through %s's haystack",
    "wonders if %s is single or transferable",
    "doesn't want any alternatives to %s",
    "writes 'I <3 U' in weedkiller on %s's lawn",
    "writes about %s in popular culture",
    "checks out %s's arse",
    "shoots Ronald Reagan to impress %s",
    "carves %s's name into its case",
    "makes billions of software copies of %s to practice seducing them",
    "fights trolls for %s",
    "swims the Hellespont for %s",
    "accidentally sends %s lewd pictures of itself using Twitter",
    "sends %s dead plant sex organs",
    "wears tinsel just for %s",
    "puts on chrome makeup for %s",
    "paints Tom Jones purple for %s",
    "buys %s a ++Rowan Bear",
    "imagines %s in a pair of Daisy Dukes",
    "wonders if %s would like to meet its sister",
    "wouldn't give a ... Castlemaine XXXX for anyone but %s",
    "hacks into a spy satellite just to get a better look at %s",
    "buys extra disk space just for pictures of %s",
    "conjugates %s",
    "offers %s a role in its new movie",
    "resolves to grass on rejs more often (at the instigation of %s)",
    "turns %s into a pillar of salt, and starts licking it",
    "assists %s with onanism",
    "gives %s a dutch rudder",
    "posts %s a French letter",
    "thinks %s could give their chair an orgasm",
    "names its pipes after %s",
    "binds its sockets to %s",
    "calls accept(2) on %s",
    "shows %s the breasts of St Agatha",
    "canonizes %s so it can make erotic sculptures of them",
    "gives %s a red hat",
    "paints devotional art of %s with no clothes on",
    "rims %s",
    "photoshops %s into its collection of Dalek porn",
    "names a Linux distribution after %s",
    "brings down the Greek economy just to get %s's attention",
    "thinks %s has a particularly well-designed ABI",
    "checks Twitter for news about %s every few minutes",
    "goes all gooey inside at the thought of %s",
    "has a warm feeling about %s",
    "buys %s transparent clothing",
    "saves the world because it has %s in it",
    "gets all starry-eyed about %s",
    "would pay the ransom if %s were ever kidnapped",
    "glances shyly at %s",
    "gets monumentally drunk and tells %s how it feels about them",
    "nominates %s for Pope",
    "buys Rockall and gives it to %s",
    "thinks peace, love, and %s are the most important things in the world",
    "buys %s a sand hopper",
    "fills %s's sand hopper",
    "admires %s's flanges",
    "admires %s's symmetry",
    "oils %s's camel",
    "wonders if %s wants to do it like they do on the Discovery Channel",
    "hopes that %s will get its message in a bottle",
    "wonders how much %s charges for a good hard shag",
    "puts a red light outside its house in the hope of attracting %s",
    "wants %s's babies",
    "affectionately nibbles %s",
    "adds leap-seconds in order to spend more time with %s",
    "makes %s's world",
    "wonders what flavour condom to buy for %s",
    "slips a porn DVD into %s's sporran",
    "carves a statue of %s",
    "changes %s's SMS alert to an erotic moan",
    "reveals the code to its safe to %s",
    "works on being more classy around %s",
    "shines %s's buttons",
    "flashes %s",
    "oils %s",
    "invites %s to the ball",
    "posts %s a pizza",
    "gives %s a blue French horn",
    "puts on a french maid's outfit and cleans %s's house from top to bottom",
    "puts on a french maid's outfit and cleans %s from top to bottom",
    "checks %s's topology",
    "checks %s for topological defects",
    "inducts over %s",
    "finds %s's fixed point",
    "integrates over %s",
    "wishes %s had a higher genus",
    "tiptoes through the tulips with %s",
    "asks to see %s's dance card",
    "presents %s with a herd of moose",
    "admires %s's valves",
    "offers %s a duck",
    "gooses %s",
    "sneaks into %s's bedroom",
    "bashfuly admits its crush on %s",
    "invites %s to join it in the shower",
    "constructs a safe space for %s",
    "wouldn't kick %s out of bed for eating biscuits",
    "buys %s a dress made of bacon",
    "dyes %s pink",
    "buys %s a pony",
    "scans all %s's ports",
    "gets drunk to cope with %s's absence",
    "founds a monarchy in order to renounce its throne for %s",
    "wants to touch %s's base",
    "paints %s purple",
    "touches %s's bum",
    "wants to ring %s's bell",
    "gives %s a kitten",
    "dedicates a sonata to %s",
    "shakes its booty for %s",
    "builds a giant telescope in order to spy upon %s",
    "proposes naming an airport in honour of %s",
    "gets married just so it can be unfaithful with %s",
    "tells %s its password",
    "lubricates itself for %s",
    "copies all %s's mannerisms",
    "practices calling itself \" Mrs % s \"",
    "compares %s's arse to Pippa Middleton's",
    "thinks %s should appear on Page Three",
    "gives %s a token ring",
    "immortalizes %s in song",
    "surveys %s",
    "builds a taller house in order to spy on %s sunbathing",
    "bites %s's neck",
    "wants to view photos of %s on a retina display",
    "trouts everything that isn't %s",
    "learns how to write \" I love % s \" in Chinese",
    "makes a mix-tape for %s",
    "makes cupcakes for %s",
    "manipulates LIBOR for %s",
    "scatters %s's enemies",
    "votes for %s",
    "tells %s what it wants, what it really really wants",
    "buys %s a bus",
    "wonders if %s is a cunning linguist",
    "sends %s a huge box of chocolates",
    "does a backflip to impress %s",
    "awards %s a gold medal",
    "would pay good money to watch %s play beach volleyball",
    "watches James Bond films to gain tips for seducing %s",
    "optimises %s",
    "thinks %s is too darn hot",
    "names an operating system after %s",
    "wonders whether there are fifty shades of %s",
    "whitelists %s",
    "wants to become overly attached to %s",
    "blows %s's whistle",
    "would carry a watermelon for %s",
    "decides to give %s a ring",
    "orders the latest iPad for %s's birthday present",
    "offers %s a bit of the old in-out in-out",
    "considers %s almost as sexy as an Aston Martin DB5",
    "tidies %s's living room floor",
    "buys %s a giant rubber duck",
    "sets up %s with its sister",
    "offers %s's father one thousand camels",
    "makes puppy-dog eyes at %s",
    "has %s's enemies shot",
    "sends %s selfies",
    "%s amat",
    "sends %s a partridge in a pear tree",
    "invites %s to bathe in a bath full of rose petals",
    "offers %s a ride in a surrey with a fringe on top",
    "rents a stretched limo for its date with %s",
    "lusts after %s, and would be prepared to commit the other deadly sins for them",
    "may not have room for a Mini, but does have room for %s",
    "puts %s in its will",
    "wonders if %s is cheaper than disk space",
    "paints %s's nipples with cochineal",
    "compares %s's beauty to that of Helen of Troy",
    "wonders how many ships %s's face would launch",
    "hopes %s is highly available",
    "considers %s wrong but romantic",
    "sends %s an anonymous Valentine's Day card",
    "imagines %s in a nurse's uniform",
    "asks the pianist to play \" As Time Goes By \" for %s",
    "gives %s a cookie",
    "thinks %s deserves a 21 gun salute",
    "knocks on %s's door and asks to see their panelling",
    "discovers an asteroid and names it after %s",
    "likes the cut of %s's jib",
    "thinks %s is better than a Kwik-Fit fitter",
    "wants to watch badgers with %s",
    "invites %s to one of its bunga bunga parties",
    "wonders whether %s will go down in the woods today",
    "offers to show %s where to buy tomatoes",
    "wolf-whistles at %s",
    "would still respect %s in the morning",
    "offers %s the gifts from \" The Twelve Days of Christmas \", all at once",
    "sets up a new TLD just for %s",
    "causes %s's wardrobe to malfunction",
    "wonders whether %s's deviation is standard",
    "promises never to trout %s",
    "invites %s out on an ISO-8601 date",
    "hopes for an expose event from %s",
    "sends an expose event to %s",
    "starts wearing purple for %s"
  ],
  csi: {
    start: [
      'The first thing we need to do is ',
      'To fix your problem, we have to ',
      'The hackers are getting in! Quickly, ',
      'To get in to the government database we\'re going to ',
      'Quickly! We have to ',
      'We can get rid of the virus, don\'t worry. First we have to '
    ],
    verb: [
      'reroute',
      'splice',
      'compile',
      'reprocess',
      'log',
      'port',
      'decrypt',
      'encrypt',
      'recode',
      'refactor',
      'import',
      'export',
      'modify',
      'uninstall',
      'install',
      'upload',
      'download',
      'open',
      'decode',
      'push',
      'recompile',
      'decompile',
      'write a GUI to track',
      'trace',
      'troubleshoot'
    ],
    noun: [
      ' the VGA cable',
      ' the USB',
      ' the browser',
      ' the interface',
      ' the Internet',
      ' the IP address',
      ' the source code',
      ' the hard drive',
      ' the RAM',
      ' the CPU',
      ' the motherboard',
      ' the monitor',
      ' the shortcut',
      ' the LAN',
      ' the Wi-Fi',
      ' the CAT5',
      ' the Bluetooth',
      ' the program',
      ' the encryption',
      ' the compiler',
      ' the IDE',
      ' Linux',
      ' Microsoft Word',
      ' the Google',
      ' the traceroute',
      ' the stack',
      ' C++',
      ' Java',
      ' JavaScript',
      ' C',
      ' C#',
      ' Python',
      ' the programming language',
      ' the SATA cable',
      ' the subnet mask',
      ' the Ethernet',
      ' the Ethernet adapter',
      ' the GPU',
      ' the keyboard',
      ' Internet Explorer',
      ' Ubuntu',
      ' the command prompt',
      ' the command line',
      ' HTTPS',
      ' FTP',
      ' SSH',
      ' Visual Basic'
    ],
    preposition: [
      ' through',
      ' into',
      ' with',
      ' on'
    ]
  }
}
