export default {
  statusCodes: {
    // nginx Codes
    "444": "No Response",
    "495": "SSL Certificate Error",
    "496": "SSL Certificate Required",
    "497": "HTTP Request Sent to HTTPS Port",
    "499": "Client Closed Request",

    // Cloudflare Codes
    "520": "Unknown Error",
    "521": "Web Server Is Down",
    "522": "Connection Timed Out",
    "523": "Origin Is Unreachable",
    "524": "A Timeout Occurred",
    "525": "SSL Handshake Failed",
    "526": "Invalid SSL Certificate",
    "527": "Railgun Error",

    // Memes
    "701": "Meh",
    "702": "Emacs",
    "703": "Explosion",
    "704": "Goto Fail",
    "705": "I wrote the code and missed the necessary validation by an oversight (see 795)",
    "706": "Delete Your Account",
    "707": "Can't quit vi",
    "710": "PHP",
    "711": "Convenience Store",
    "712": "NoSQL",
    "718": "I am not a teapot",
    "719": "Haskell",
    "720": "Unpossible",
    "721": "Known Unknowns",
    "722": "Unknown Unknowns",
    "723": "Tricky",
    "724": "This line should be unreachable",
    "725": "It works on my machine",
    "726": "It's a feature, not a bug",
    "727": "32 bits is plenty",
    "728": "Go Fish",
    "730": "Fucking Bower",
    "731": "Fucking Rubygems",
    "732": "Fucking Unic💩de",
    "733": "Fucking Deadlocks",
    "734": "Fucking Deferreds",
    "735": "Fucking IE",
    "736": "Fucking Race Conditions",
    "737": "FuckThreadsing",
    "738": "Fucking Bundler",
    "739": "Fucking Windows",
    "740": "Computer says no",
    "741": "Compiling",
    "742": "A kitten dies",
    "743": "I thought I knew regular expressions",
    "744": "Y U NO write integration tests?",
    "745": "I don't always test my code, but when I do I do it in production",
    "746": "Missed Ballmer Peak",
    "747": "Motherfucking Snakes on the Motherfucking Plane",
    "748": "Confounded by Ponies",
    "749": "Reserved for Chuck Norris",
    "750": "Didn't bother to compile it",
    "753": "Syntax Error",
    "754": "Too many semi",
    "755": "Not enough semi",
    "756": "Insufficiently polite",
    "757": "Excessively polite",
    "759": "Unexpected T_PAAMAYIM_NEKUDOTAYIM",
    "761": "Hungover",
    "762": "Stoned",
    "763": "Under",
    "764": "Over",
    "765": "Railscamp",
    "766": "Sober",
    "767": "Drunk",
    "768": "Accidentally Took Sleeping Pills Instead Of Migraine Pills During Crunch Week",
    "769": "Questionable Maturity Level",
    "771": "Cached for too long",
    "772": "Not cached long enough",
    "773": "Not cached at all",
    "774": "Why was this cached?",
    "775": "Out of cash",
    "776": "Error on the Exception",
    "777": "Coincidence",
    "778": "Off By One Error",
    "779": "Off By Too Many To Count Error",
    "780": "Project owner not responding",
    "781": "Operations",
    "782": "QA",
    "783": "It was a customer request, honestly",
    "784": "Management, obviously",
    "785": "TPS Cover Sheet not attached",
    "786": "Try it now",
    "787": "Further Funding Required",
    "788": "Designer's final designs weren't",
    "789": "Not my department",
    "791": "The Internet shut down due to copyright restrictions",
    "792": "Climate change driven catastrophic weather event",
    "793": "Zombie Apocalypse",
    "794": "Someone let PG near a REPL",
    "795": "#heartbleed (see 705)",
    "797": "This is the last page of the Internet. Go back",
    "799": "End of the world"
  },
  clap: {
    sincere: ["http://i.imgur.com/pfrtv6H.gif", "http://i.imgur.com/Bp4P8l3.gif", "http://i.imgur.com/v7mZ22P.gif", "http://i.imgur.com/S1v4KuY.gif", "http://i.imgur.com/YTaSAkq.gif", "http://i.imgur.com/JO6Wz3r.gif", "http://i.imgur.com/pWEd6cF.gif", "http://i.imgur.com/zumSlIA.gif", "http://i.imgur.com/RGczKmV.gif", "http://i.imgur.com/KAQhoCm.gif", "http://i.imgur.com/PASRKXo.gif", "http://i.imgur.com/ZOWQTO6.gif", "http://i.imgur.com/cY0eH5c.gif", "http://i.imgur.com/wf5qvOM.gif", "http://i.imgur.com/9Zv4V.gif", "http://i.imgur.com/t8zvc.gif", "http://cache.blippitt.com/wp-content/uploads/2012/06/Daily-Life-GIFs-06-The-Rock-Clapping.gif", "http://25.media.tumblr.com/tumblr_m00e9mCyWj1rqtbn0o1_500.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/Kurtclapping.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/riker.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/hp3.gif", "http://assets0.ordienetworks.com/images/GifGuide/clapping/1292223254212-dumpfm-mario-Obamaclap.gif", "http://www.reactiongifs.com/wp-content/uploads/2013/01/applause.gif", "http://stream1.gifsoup.com/view7/4263859/billy-madison-clapping-o.gif"],
    insincere: ["http://i.imgur.com/2QXgcqP.gif", "http://i.imgur.com/Yih2Lcg.gif", "http://i.imgur.com/un3MuET.gif", "http://i.imgur.com/H2wPc1d.gif", "http://i.imgur.com/uOtALBE.gif", "http://i.imgur.com/nmqrdiF.gif", "http://i.imgur.com/GgxOUGt.gif", "http://i.imgur.com/wyTQMD6.gif", "http://i.imgur.com/GYRGOy6.gif", "http://i.imgur.com/ojIsLUA.gif", "http://i.imgur.com/bRetADl.gif", "http://i.imgur.com/814mkEC.gif", "http://i.imgur.com/uYryMyr.gif", "http://i.imgur.com/YfrikPR.gif", "http://i.imgur.com/sBEFqYR.gif", "http://i.imgur.com/Sx8iAS8.gif", "http://i.imgur.com/5zKXz.gif"]
  },
  flirts: [
    "covers %s in blancmange",
    "jumps for joy at the thought of %s",
    "offers %s a bunch of flowers",
    "blows kisses at %s",
    "falls head over heels in love with %s",
    "offers to take %s out for dinner",
    "is %s's kind of robot",
    "offers %s a Turkish Delight",
    "gazes contentedly at %s",
    "offers %s a cherry",
    "imagines %s in a tutu",
    "catches %s's eye across a crowded room",
    "kisses %s's hand",
    "wonders what a nice person like %s is doing in a place like this",
    "licks chocolate sauce off %s",
    "gets down on one knee in front of %s",
    "bats its eyelashes at %s",
    "winks suggestively at %s",
    "blabbers incoherently at the sight of %s",
    "mentally undresses %s",
    "daydreams about %s",
    "wonders what %s is really thinking",
    "gazes mutely into %s's eyes",
    "wonders if %s might reciprocate its feelings",
    "whispers sweet nothings to %s",
    "sends %s a red rose",
    "toasts %s with champagne",
    "offers %s its last Rolo",
    "invites %s up for coffee",
    "promises %s a night to remember",
    "invites %s in to see its etchings",
    "wonders if %s is really that innocent",
    "serenades %s",
    "puts a rose between its teeth and tangoes seductively with %s",
    "plays with its hair whilst gazing at %s",
    "draws a magic circle around itself and %s",
    "tickles %s playfully",
    "draws a flattering portrait of %s",
    "poings happily at the sight of %s",
    "gives %s a high-five",
    "brushes lint off %s's clothing",
    "dims the lights for %s",
    "invites %s behind the bike sheds",
    "rides a tightrope on a unicycle while juggling chainsaws in an attempt to impress %s",
    "composes haiku for %s",
    "makes the tea for %s",
    "sprinkles %s with hundreds and thousands",
    "flagellates %s with a birch branch",
    "<3s %s",
    "admires %s's boots",
    "invites %s to a candle-lit dinner",
    "hopes %s packed their toothbrush!",
    "showers %s in rose petals",
    "holds a candle for %s",
    "admires %s's physique",
    "gives %s a nice relaxing foot massage",
    "treks through the jungle to deliver Milk Tray to %s",
    "searches for a rhyme for its poem about %s",
    "compares %s's eyes to stars",
    "wonders whether %s comes here often?",
    "compares %s to a summer's day",
    "curls up at %s's feet",
    "plays %s's theme tune",
    "sends for %s and more golden syrup",
    "puts %s on top of the Christmas tree",
    "writes flirts just for %s",
    "thinks %s is the new hotness",
    "imagines %s in a sailor outfit",
    "would like to cause earthquakes with %s",
    "creates an \" I bet we can get a million people who fancy % s \" group on Facebook",
    "becomes a fan of %s",
    "turns down the house lights for %s",
    "invites %s up to see its iPad",
    "can't wait to unbox %s",
    "blows %s's vuvuzela",
    "wonders if %s is multi-touch",
    "tips its hat to %s",
    "would Photoshop %s but they are perfect already",
    "would betray its country for %s",
    "creates a dozen extra Twitter accounts just to follow %s",
    "wears sexy underwear just for %s",
    "is never gonna give %s up",
    "wants to FaceTime %s",
    "spies on %s through their webcam",
    "dyes its hair for %s",
    "newgroups alt.fan.%s",
    "tattoos %s's name on its bottom",
    "makes a backup copy of %s",
    "throws itself at %s's feet",
    "buys %s a nice dress",
    "buys %s a revealing dress",
    "asks %s out on a date",
    "posts pictures of %s to rule34.paheal.net [NWS!]",
    "emails %s its favourite cat pictures",
    "lends %s all its spoons",
    "searches the internet for pictures of %s",
    "writes to Dan Savage for tips on seducing %s",
    "cross-dresses just for %s",
    "buys a telephoto lens just to take pictures of %s",
    "offers %s some Madeira",
    "offers %s a fork",
    "gives %s a thumbs-up",
    "goes speed-dating with a dozen clones of %s",
    "writes a webcomic about the adventures of %s",
    "dresses up as Batman for %s",
    "club mammoth for %s. Ug!",
    "sexts %s",
    "defeats all of %s's evil exes",
    "clones %s's repo",
    "thinks %s is cuter than all the My Little Ponies put together",
    "would open the pod bay doors for %s",
    "takes upskirt photos of %s",
    "sniffs %s's underwear",
    "writes thousands of lines of elisp just for %s",
    "showers %s with porcelain sunflower seeds",
    "creates a .xxx domain just for %s",
    "hopes rule 34 applies to %s",
    "unzips %s",
    "drives its tractor through %s's haystack",
    "wonders if %s is single or transferable",
    "doesn't want any alternatives to %s",
    "writes 'I <3 U' in weedkiller on %s's lawn",
    "writes about %s in popular culture",
    "checks out %s's arse",
    "shoots Ronald Reagan to impress %s",
    "carves %s's name into its case",
    "makes billions of software copies of %s to practice seducing them",
    "fights trolls for %s",
    "swims the Hellespont for %s",
    "accidentally sends %s lewd pictures of itself using Twitter",
    "sends %s dead plant sex organs",
    "wears tinsel just for %s",
    "puts on chrome makeup for %s",
    "paints Tom Jones purple for %s",
    "buys %s a ++Rowan Bear",
    "imagines %s in a pair of Daisy Dukes",
    "wonders if %s would like to meet its sister",
    "wouldn't give a ... Castlemaine XXXX for anyone but %s",
    "hacks into a spy satellite just to get a better look at %s",
    "buys extra disk space just for pictures of %s",
    "conjugates %s",
    "offers %s a role in its new movie",
    "resolves to grass on rejs more often (at the instigation of %s)",
    "turns %s into a pillar of salt, and starts licking it",
    "assists %s with onanism",
    "gives %s a dutch rudder",
    "posts %s a French letter",
    "thinks %s could give their chair an orgasm",
    "names its pipes after %s",
    "binds its sockets to %s",
    "calls accept(2) on %s",
    "shows %s the breasts of St Agatha",
    "canonizes %s so it can make erotic sculptures of them",
    "gives %s a red hat",
    "paints devotional art of %s with no clothes on",
    "rims %s",
    "photoshops %s into its collection of Dalek porn",
    "names a Linux distribution after %s",
    "brings down the Greek economy just to get %s's attention",
    "thinks %s has a particularly well-designed ABI",
    "checks Twitter for news about %s every few minutes",
    "goes all gooey inside at the thought of %s",
    "has a warm feeling about %s",
    "buys %s transparent clothing",
    "saves the world because it has %s in it",
    "gets all starry-eyed about %s",
    "would pay the ransom if %s were ever kidnapped",
    "glances shyly at %s",
    "gets monumentally drunk and tells %s how it feels about them",
    "nominates %s for Pope",
    "buys Rockall and gives it to %s",
    "thinks peace, love, and %s are the most important things in the world",
    "buys %s a sand hopper",
    "fills %s's sand hopper",
    "admires %s's flanges",
    "admires %s's symmetry",
    "oils %s's camel",
    "wonders if %s wants to do it like they do on the Discovery Channel",
    "hopes that %s will get its message in a bottle",
    "wonders how much %s charges for a good hard shag",
    "puts a red light outside its house in the hope of attracting %s",
    "wants %s's babies",
    "affectionately nibbles %s",
    "adds leap-seconds in order to spend more time with %s",
    "makes %s's world",
    "wonders what flavour condom to buy for %s",
    "slips a porn DVD into %s's sporran",
    "carves a statue of %s",
    "changes %s's SMS alert to an erotic moan",
    "reveals the code to its safe to %s",
    "works on being more classy around %s",
    "shines %s's buttons",
    "flashes %s",
    "oils %s",
    "invites %s to the ball",
    "posts %s a pizza",
    "gives %s a blue French horn",
    "puts on a french maid's outfit and cleans %s's house from top to bottom",
    "puts on a french maid's outfit and cleans %s from top to bottom",
    "checks %s's topology",
    "checks %s for topological defects",
    "inducts over %s",
    "finds %s's fixed point",
    "integrates over %s",
    "wishes %s had a higher genus",
    "tiptoes through the tulips with %s",
    "asks to see %s's dance card",
    "presents %s with a herd of moose",
    "admires %s's valves",
    "offers %s a duck",
    "gooses %s",
    "sneaks into %s's bedroom",
    "bashfuly admits its crush on %s",
    "invites %s to join it in the shower",
    "constructs a safe space for %s",
    "wouldn't kick %s out of bed for eating biscuits",
    "buys %s a dress made of bacon",
    "dyes %s pink",
    "buys %s a pony",
    "scans all %s's ports",
    "gets drunk to cope with %s's absence",
    "founds a monarchy in order to renounce its throne for %s",
    "wants to touch %s's base",
    "paints %s purple",
    "touches %s's bum",
    "wants to ring %s's bell",
    "gives %s a kitten",
    "dedicates a sonata to %s",
    "shakes its booty for %s",
    "builds a giant telescope in order to spy upon %s",
    "proposes naming an airport in honour of %s",
    "gets married just so it can be unfaithful with %s",
    "tells %s its password",
    "lubricates itself for %s",
    "copies all %s's mannerisms",
    "practices calling itself \" Mrs % s \"",
    "compares %s's arse to Pippa Middleton's",
    "thinks %s should appear on Page Three",
    "gives %s a token ring",
    "immortalizes %s in song",
    "surveys %s",
    "builds a taller house in order to spy on %s sunbathing",
    "bites %s's neck",
    "wants to view photos of %s on a retina display",
    "trouts everything that isn't %s",
    "learns how to write \" I love % s \" in Chinese",
    "makes a mix-tape for %s",
    "makes cupcakes for %s",
    "manipulates LIBOR for %s",
    "scatters %s's enemies",
    "votes for %s",
    "tells %s what it wants, what it really really wants",
    "buys %s a bus",
    "wonders if %s is a cunning linguist",
    "sends %s a huge box of chocolates",
    "does a backflip to impress %s",
    "awards %s a gold medal",
    "would pay good money to watch %s play beach volleyball",
    "watches James Bond films to gain tips for seducing %s",
    "optimises %s",
    "thinks %s is too darn hot",
    "names an operating system after %s",
    "wonders whether there are fifty shades of %s",
    "whitelists %s",
    "wants to become overly attached to %s",
    "blows %s's whistle",
    "would carry a watermelon for %s",
    "decides to give %s a ring",
    "orders the latest iPad for %s's birthday present",
    "offers %s a bit of the old in-out in-out",
    "considers %s almost as sexy as an Aston Martin DB5",
    "tidies %s's living room floor",
    "buys %s a giant rubber duck",
    "sets up %s with its sister",
    "offers %s's father one thousand camels",
    "makes puppy-dog eyes at %s",
    "has %s's enemies shot",
    "sends %s selfies",
    "%s amat",
    "sends %s a partridge in a pear tree",
    "invites %s to bathe in a bath full of rose petals",
    "offers %s a ride in a surrey with a fringe on top",
    "rents a stretched limo for its date with %s",
    "lusts after %s, and would be prepared to commit the other deadly sins for them",
    "may not have room for a Mini, but does have room for %s",
    "puts %s in its will",
    "wonders if %s is cheaper than disk space",
    "paints %s's nipples with cochineal",
    "compares %s's beauty to that of Helen of Troy",
    "wonders how many ships %s's face would launch",
    "hopes %s is highly available",
    "considers %s wrong but romantic",
    "sends %s an anonymous Valentine's Day card",
    "imagines %s in a nurse's uniform",
    "asks the pianist to play \" As Time Goes By \" for %s",
    "gives %s a cookie",
    "thinks %s deserves a 21 gun salute",
    "knocks on %s's door and asks to see their panelling",
    "discovers an asteroid and names it after %s",
    "likes the cut of %s's jib",
    "thinks %s is better than a Kwik-Fit fitter",
    "wants to watch badgers with %s",
    "invites %s to one of its bunga bunga parties",
    "wonders whether %s will go down in the woods today",
    "offers to show %s where to buy tomatoes",
    "wolf-whistles at %s",
    "would still respect %s in the morning",
    "offers %s the gifts from \" The Twelve Days of Christmas \", all at once",
    "sets up a new TLD just for %s",
    "causes %s's wardrobe to malfunction",
    "wonders whether %s's deviation is standard",
    "promises never to trout %s",
    "invites %s out on an ISO-8601 date",
    "hopes for an expose event from %s",
    "sends an expose event to %s",
    "starts wearing purple for %s"
  ],
  csi: {
    start: [
      'The first thing we need to do is ',
      'To fix your problem, we have to ',
      'The hackers are getting in! Quickly, ',
      'To get in to the government database we\'re going to ',
      'Quickly! We have to ',
      'We can get rid of the virus, don\'t worry. First we have to '
    ],
    verb: [
      'reroute',
      'splice',
      'compile',
      'reprocess',
      'log',
      'port',
      'decrypt',
      'encrypt',
      'recode',
      'refactor',
      'import',
      'export',
      'modify',
      'uninstall',
      'install',
      'upload',
      'download',
      'open',
      'decode',
      'push',
      'recompile',
      'decompile',
      'write a GUI to track',
      'trace',
      'troubleshoot'
    ],
    noun: [
      ' the VGA cable',
      ' the USB',
      ' the browser',
      ' the interface',
      ' the Internet',
      ' the IP address',
      ' the source code',
      ' the hard drive',
      ' the RAM',
      ' the CPU',
      ' the motherboard',
      ' the monitor',
      ' the shortcut',
      ' the LAN',
      ' the Wi-Fi',
      ' the CAT5',
      ' the Bluetooth',
      ' the program',
      ' the encryption',
      ' the compiler',
      ' the IDE',
      ' Linux',
      ' Microsoft Word',
      ' the Google',
      ' the traceroute',
      ' the stack',
      ' C++',
      ' Java',
      ' JavaScript',
      ' C',
      ' C#',
      ' Python',
      ' the programming language',
      ' the SATA cable',
      ' the subnet mask',
      ' the Ethernet',
      ' the Ethernet adapter',
      ' the GPU',
      ' the keyboard',
      ' Internet Explorer',
      ' Ubuntu',
      ' the command prompt',
      ' the command line',
      ' HTTPS',
      ' FTP',
      ' SSH',
      ' Visual Basic'
    ],
    preposition: [
      ' through',
      ' into',
      ' with',
      ' on'
    ]
  },
  pugs: [
    "https://i.imgur.com/oeAE6v9.jpg",
    "https://i.imgur.com/UPGJ7aw.jpg",
    "https://i.imgur.com/K4L9hDd.jpg",
    "https://i.imgur.com/ZQ8lETY.jpg",
    "https://i.imgur.com/iT7FvNL.jpg",
    "https://i.imgur.com/NaUTei9.jpg",
    "https://i.imgur.com/6Ei9Ke8.jpg",
    "https://i.imgur.com/uSIYIaI.jpg",
    "https://i.imgur.com/LHC81X5.jpg",
    "https://i.imgur.com/VThCzL1.jpg",
    "https://i.imgur.com/5pHRWH0.jpg",
    "https://i.imgur.com/jyJWGrK.jpg",
    "https://i.imgur.com/oRAsDJJ.jpg",
    "https://i.imgur.com/Ve0ajQt.jpg",
    "https://i.imgur.com/bvmu8ay.jpg",
    "https://i.imgur.com/Ecp0lb0.jpg",
    "https://i.imgur.com/aYRJRIt.jpg",
    "https://i.imgur.com/6xL9Ebu.jpg",
    "https://i.imgur.com/56KxYeQ.jpg",
    "https://i.imgur.com/sntjWRd.jpg",
    "https://i.imgur.com/x7xyahE.jpg",
    "https://i.imgur.com/m5zRXC9.jpg",
    "https://i.imgur.com/KG56oE3.jpg",
    "https://i.imgur.com/Vw7sjSj.jpg",
    "https://i.imgur.com/mNsKmTA.jpg",
    "https://i.imgur.com/XLvHD1M.jpg",
    "https://i.imgur.com/lWvN3Ms.jpg",
    "https://i.imgur.com/FziNgqj.jpg",
    "https://i.imgur.com/IMLmzM6.jpg",
    "https://i.imgur.com/CpWeSsH.jpg",
    "https://i.imgur.com/7JfYfSv.jpg",
    "https://i.imgur.com/cR98sQ2.jpg",
    "https://i.imgur.com/1UfpdYe.jpg",
    "https://i.imgur.com/gSc7o9s.jpg",
    "https://i.imgur.com/HuV5KRA.jpg",
    "https://i.imgur.com/UqHUEbr.jpg",
    "https://i.imgur.com/wLTe4Rq.jpg",
    "https://i.imgur.com/mIlKHL2.png",
    "https://i.imgur.com/8YLLAHC.jpg",
    "https://i.imgur.com/faPwL5D.jpg",
    "https://i.imgur.com/4uOIsF9.jpg",
    "https://i.imgur.com/oJstKux.jpg",
    "https://i.imgur.com/OI9OpTY.jpg",
    "https://i.imgur.com/QTwXLdW.jpg",
    "https://i.imgur.com/qFVS9rs.jpg",
    "https://i.imgur.com/WAfjwwi.jpg",
    "https://i.imgur.com/6es5RXz.jpg",
    "https://i.imgur.com/NqFauFG.jpg",
    "https://i.imgur.com/NsG2ytg.jpg",
    "https://i.imgur.com/znPGWq6.jpg",
    "https://i.imgur.com/FpLRELo.jpg",
    "https://i.imgur.com/mBAIf9n.jpg",
    "https://i.imgur.com/j4RnK9o.jpg",
    "https://i.imgur.com/ZT9HNy3.jpg",
    "https://i.imgur.com/Bdf4YoR.jpg",
    "https://i.imgur.com/r2UIZ8C.jpg",
    "https://i.imgur.com/PWTnqnP.jpg",
    "https://i.imgur.com/lhGIgAJ.jpg",
    "https://i.imgur.com/o7gtoyB.jpg",
    "https://i.imgur.com/KML5i1Y.jpg",
    "https://i.imgur.com/KLMISDk.jpg",
    "https://i.imgur.com/nQLKwCx.jpg",
    "https://i.imgur.com/nS9dBZ9.jpg",
    "https://i.imgur.com/dYLjq7f.jpg",
    "https://i.imgur.com/LIX2lDk.jpg",
    "https://i.imgur.com/TMqqXvu.jpg",
    "https://i.imgur.com/HarjVQP.jpg",
    "https://i.imgur.com/TuWqRrK.jpg",
    "https://i.imgur.com/yROXrFp.jpg",
    "https://i.imgur.com/GZNnc50.jpg",
    "https://i.imgur.com/sVwmTAN.jpg",
    "https://i.imgur.com/5spVLSX.jpg",
    "https://i.imgur.com/TtkWnIl.jpg",
    "https://i.imgur.com/I7Wor8V.jpg",
    "https://i.imgur.com/pvPD5Lk.jpg",
    "https://i.imgur.com/i8N7Ie9.jpg",
    "https://i.imgur.com/cs3gpVQ.jpg",
    "https://i.imgur.com/EnZ2G2s.jpg",
    "https://i.imgur.com/opXWk61.jpg",
    "https://i.imgur.com/XaYp2AH.jpg",
    "https://i.imgur.com/FhWzjeG.jpg",
    "https://i.imgur.com/4sWAiKZ.jpg",
    "https://i.imgur.com/2VpNS1o.jpg",
    "https://i.imgur.com/8MASvkS.jpg",
    "https://i.imgur.com/PwTfzN4.jpg",
    "https://i.imgur.com/OSghVOn.jpg",
    "https://i.imgur.com/lM8rhjO.jpg",
    "https://i.imgur.com/mSL6fK2.jpg",
    "https://i.imgur.com/wRLkvS9.jpg",
    "https://i.imgur.com/HIfGMeE.jpg",
    "https://i.imgur.com/RKDvN7F.jpg",
    "https://i.imgur.com/up0ZKng.jpg",
    "https://i.imgur.com/jo70l8A.jpg",
    "https://i.imgur.com/sGNNmkc.jpg",
    "https://i.imgur.com/l9CmyQp.jpg",
    "https://i.imgur.com/kgAcOH6.jpg",
    "https://i.imgur.com/m4LipBJ.jpg",
    "https://i.imgur.com/0exkebs.jpg",
    "https://i.imgur.com/o9pzjzd.jpg",
    "https://i.imgur.com/P01vv52.jpg",
    "https://i.imgur.com/18UoLZ5.jpg",
    "https://i.imgur.com/MPFcUfz.jpg",
    "https://i.imgur.com/OyKefp6.jpg",
    "https://i.imgur.com/UfpsoEr.jpg",
    "https://i.imgur.com/z0nWdlv.jpg",
    "https://i.imgur.com/JmDIpZM.jpg",
    "https://i.imgur.com/bdAYqlP.jpg",
    "https://i.imgur.com/c95lPLV.jpg",
    "https://i.imgur.com/CV9coM7.jpg",
    "https://i.imgur.com/3BKsWol.jpg",
    "https://i.imgur.com/JfFBbLh.jpg",
    "https://i.imgur.com/Bn9HBgO.jpg",
    "https://i.imgur.com/l7N17ls.jpg",
    "https://i.imgur.com/EREuqJ5.jpg",
    "https://i.imgur.com/fDZx0eO.jpg",
    "https://i.imgur.com/HFTqNJQ.jpg",
    "https://i.imgur.com/nIkfk6V.jpg",
    "https://i.imgur.com/askyW5q.jpg",
    "https://i.imgur.com/1fuYJTC.jpg",
    "https://i.imgur.com/ATx6mmt.jpg",
    "https://i.imgur.com/WyTpKgq.jpg",
    "https://i.imgur.com/BciH5TE.jpg",
    "https://i.imgur.com/BCDuL6D.jpg",
    "https://i.imgur.com/sdT9cVX.jpg",
    "https://i.imgur.com/IuNEPNc.jpg",
    "https://i.imgur.com/UHSRqDf.jpg",
    "https://i.imgur.com/anX3xQ6.jpg",
    "https://i.imgur.com/Z1ADvbe.jpg",
    "https://i.imgur.com/CgzJoBW.jpg",
    "https://i.imgur.com/Ba0JZpq.jpg",
    "https://i.imgur.com/OoDAOQA.jpg",
    "https://i.imgur.com/SUXsrGh.jpg",
    "https://i.imgur.com/qCqi8Et.jpg",
    "https://i.imgur.com/kBXquD1.jpg",
    "https://i.imgur.com/E5JUUFo.jpg",
    "https://i.imgur.com/dbDyrvS.jpg",
    "https://i.imgur.com/2ioPRj3.jpg",
    "https://i.imgur.com/61QtJq1.jpg",
    "https://i.imgur.com/4jGV9C5.jpg",
    "https://i.imgur.com/RrnrVKm.jpg",
    "https://i.imgur.com/wdZPUsM.jpg",
    "https://i.imgur.com/ZzvYyuo.jpg",
    "https://i.imgur.com/9TlmgAC.jpg",
    "https://i.imgur.com/N9mFWNd.jpg",
    "https://i.imgur.com/IIRRlrn.jpg",
    "https://i.imgur.com/jtaWLjW.jpg",
    "https://i.imgur.com/FFvNfdo.jpg",
    "https://i.imgur.com/KNz45ri.jpg",
    "https://i.imgur.com/oBmFR0i.jpg",
    "https://i.imgur.com/DcpGHtJ.png",
    "https://i.imgur.com/EdqzO4Q.jpg",
    "https://i.imgur.com/4tXEIcB.jpg",
    "https://i.imgur.com/QSphzZs.jpg",
    "https://i.imgur.com/KHiRCj1.jpg",
    "https://i.imgur.com/mKPHPtp.jpg",
    "https://i.imgur.com/2WtzITP.jpg",
    "https://i.imgur.com/uY594Ra.jpg",
    "https://i.imgur.com/pOFKfcz.jpg",
    "https://i.imgur.com/lL1LC5N.jpg",
    "https://i.imgur.com/zoVIAy0.jpg",
    "https://i.imgur.com/SOKiXe8.jpg",
    "https://i.imgur.com/5id4fUS.jpg",
    "https://i.imgur.com/4ORrLNr.jpg",
    "https://i.imgur.com/t7DTVZa.jpg",
    "https://i.imgur.com/pkDPYEn.jpg",
    "https://i.imgur.com/aSIZwlP.jpg",
    "https://i.imgur.com/GgdgGxb.jpg",
    "https://i.imgur.com/jp9OPeg.jpg",
    "https://i.imgur.com/pcCgzJn.jpg",
    "https://i.imgur.com/uLA5YkP.jpg",
    "https://i.imgur.com/mrlOC4Y.jpg",
    "https://i.imgur.com/JGHkvrx.jpg",
    "https://i.imgur.com/wpOxtop.jpg",
    "https://i.imgur.com/gY00shr.jpg",
    "https://i.imgur.com/C3rreb4.jpg",
    "https://i.imgur.com/zVo4xsD.jpg",
    "https://i.imgur.com/lJy44f9.jpg",
    "https://i.imgur.com/WcEq8g4.jpg",
    "https://i.imgur.com/K8i5ua9.jpg",
    "https://i.imgur.com/tB2cY6w.jpg",
    "https://i.imgur.com/6jjlIwM.jpg",
    "https://i.imgur.com/wX8Kf1L.jpg",
    "https://i.imgur.com/QE4pMXb.jpg",
    "https://i.imgur.com/djyVdTX.jpg",
    "https://i.imgur.com/DJmlXsp.jpg",
    "https://i.imgur.com/OvBBV15.jpg",
    "https://i.imgur.com/DDat2Oq.jpg",
    "https://i.imgur.com/vNnvXde.jpg",
    "https://i.imgur.com/bLDx3gK.jpg",
    "https://i.imgur.com/D1LpQwi.jpg",
    "https://i.imgur.com/tWewUo4.jpg",
    "https://i.imgur.com/NLFz4y4.jpg",
    "https://i.imgur.com/r3EbyFu.png",
    "https://i.imgur.com/Xweo3og.png",
    "https://i.imgur.com/vpKJj5N.jpg",
    "https://i.imgur.com/l9uc0rN.jpg",
    "https://i.imgur.com/Sk6hsMy.jpg",
    "https://i.imgur.com/IRB4g5w.jpg",
    "https://i.imgur.com/UenhW5x.jpg",
    "https://i.imgur.com/N2OcbVb.jpg",
    "https://i.imgur.com/8mdMqcG.jpg",
    "https://i.imgur.com/kM1Cft2.jpg",
    "https://i.imgur.com/igckX3h.jpg",
    "https://i.imgur.com/mYGqIfe.jpg",
    "https://i.imgur.com/GcrI9ra.jpg",
    "https://i.imgur.com/DYTebTd.jpg",
    "https://i.imgur.com/xGppc4f.jpg",
    "https://i.imgur.com/lMklyjk.jpg",
    "https://i.imgur.com/t62FwPG.jpg",
    "https://i.imgur.com/nCMvEwb.jpg",
    "https://i.imgur.com/TgcQ7JS.jpg",
    "https://i.imgur.com/IS927tQ.jpg",
    "https://i.imgur.com/mdyaDb8.jpg",
    "https://i.imgur.com/s3tDbyJ.jpg",
    "https://i.imgur.com/fX6Qavj.jpg",
    "https://i.imgur.com/gx3v39R.jpg",
    "https://i.imgur.com/FdabzU6.jpg",
    "https://i.imgur.com/l9zFcK1.jpg",
    "https://i.imgur.com/XaLHvnw.png",
    "https://i.imgur.com/IljttXN.jpg",
    "https://i.imgur.com/0GLN5ry.jpg",
    "https://i.imgur.com/n6YacaC.jpg",
    "https://i.imgur.com/nFHQtrR.jpg",
    "https://i.imgur.com/eFiwXmJ.jpg",
    "https://i.imgur.com/NYqc0Vx.jpg",
    "https://i.imgur.com/keWa3tk.jpg",
    "https://i.imgur.com/V04A27H.jpg",
    "https://i.imgur.com/jWKv5fr.jpg",
    "https://i.imgur.com/rNqcAYA.jpg",
    "https://i.imgur.com/ZLlzbm8.jpg",
    "https://i.imgur.com/F4gBTlL.jpg",
    "https://i.imgur.com/XdKx3Ys.jpg",
    "https://i.imgur.com/o3UBHH5.png",
    "https://i.imgur.com/qtBXFGI.jpg",
    "https://i.imgur.com/7KV3tLe.jpg",
    "https://i.imgur.com/fCilCws.jpg",
    "https://i.imgur.com/vYAHpDo.jpg",
    "https://i.imgur.com/uuzB5rv.jpg",
    "https://i.imgur.com/ycTNUlP.jpg",
    "https://i.imgur.com/gYsnc6s.jpg",
    "https://i.imgur.com/ZKhWm50.jpg",
    "https://i.imgur.com/wMLPiYB.jpg",
    "https://i.imgur.com/edK5JL2.jpg",
    "https://i.imgur.com/oBxzepO.jpg",
    "https://i.imgur.com/t3vBUJR.jpg",
    "https://i.imgur.com/gTwLcfx.jpg",
    "https://i.imgur.com/4b9p0wF.jpg",
    "https://i.imgur.com/9TXs351.jpg",
    "https://i.imgur.com/qxBQo2w.png",
    "https://i.imgur.com/1zgaHfU.jpg",
    "https://i.imgur.com/k1ma4UD.jpg",
    "https://i.imgur.com/fBZJIyA.jpg",
    "https://i.imgur.com/ac8I8n3.jpg",
    "https://i.imgur.com/7qwLIAX.jpg",
    "https://i.imgur.com/rk1aT8I.jpg",
    "https://i.imgur.com/0wB8Ls2.jpg",
    "https://i.imgur.com/oFeQCZr.jpg",
    "https://i.imgur.com/d27XmsF.jpg",
    "https://i.imgur.com/LHV4I1J.jpg",
    "https://i.imgur.com/wuUj168.jpg",
    "https://i.imgur.com/jhihVNG.jpg",
    "https://i.imgur.com/5wwPkEg.jpg",
    "https://i.imgur.com/z9livSa.jpg",
    "https://i.imgur.com/cwz4DZk.jpg",
    "https://i.imgur.com/OSO4VLG.jpg"
  ],
  roasts: [
    "You cock sucking, useless, idiot.",
    "Shut up, you'll never be the man your mother is.",
    "You're a failed abortion whose birth certificate is an apology from the condom factory.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "Your family tree is a cactus, because everybody on it is a prick.",
    "You're so ugly Hello Kitty said goodbye to you.",
    "It looks like your face caught on fire and someone tried to put it out with a fork.",
    "You are so ugly that when your mama dropped you off at school she got a fine for littering.",
    "If you were twice as smart, you'd still be retarded.",
    "Your so ugly when you popped out the doctor said aww what a treasure and your mom said yeah lets bury it.",
    "God made you as an example of what not to do",
    "We all sprang from apes, but you didn't spring far enough.",
    "I hear when you were a child your mother wanted to hire somebody to take care of you, but the mafia wanted too much.",
    "I would ask how old you are, but I know you can't count that high.",
    "Out of 100,000 sperm, you were the fastest?",
    "If you really want to know about mistakes, you should ask your parents.",
    "I could eat a bowl of alphabet soup and crap out a smarter comeback than what you just said.",
    "Hey, you have something on your chin...3rd one down.",
    "When you were born, the police arrested your dad, the doctor slapped your mom, animal control euthanized your brother, and A&E made a documentary that saved your life.",
    "Your mamma so fat she has to wear 2 watches because she covers two time zones.",
    "You're so fat the only letters of the alphabet you know are KFC.",
    "You're so fat you need cheat codes to play Wii Fit.",
    "With a face like yours, I wish I was blind.",
    "Do you still love nature....despite what it did to you?",
    "Why don't you check up on eBay and see if they have a life for sale.",
    "You must be the arithmetic man; you add trouble, subtract pleasure, divide attention, and multiply ignorance.",
    "The only positive thing about you is your HIV status.",
    "Is that your face? Or did your neck just throw up?",
    "Here's 20 cents, call all your friends and give me back the change.",
    "Two wrongs don't make a right, take your parents as an example.",
    "Your mom is so stupid she tried to wake a sleeping bag.",
    "Please, I could remove 90% of your 'beauty' with a tissue",
    "Why don't you slip into something more comfortable? Like a coma.",
    "Yo mama so fat wen she jumped in the ocean the whales started singing We Are Family.",
    "The only thing that goes erect when I'm near you is my middle finger.",
    "All the branches fell off your family tree when you were born.",
    "You're like STDs, nobody wants you, everyone hates you and it proves your parents should have used protection.",
    "Are you always an idiot or just when I'm around?",
    "If I wanted to kill myself, I could just climb up to your ego and jump down to your IQ level.",
    "Haha... Why would you take a snack to school if you're gonna lose your brain in it?",
    "I would call you a dick, but you don't have one.",
    "You wanna roast? Sorry, no. I have too much fire, and I don't want to kill somebody.",
    "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    "Calling me a bitch? I'm not your mom.",
    "Has your face always looked like that? Or did you just get surgery to make it look worse then trash?",
    "Why call me an ass if you came out of my ass? You piece of shit.",
    "If you are calling me a dick, are talking about you? Or your mom?",
    "Your hairline.",
    "Your skill is equal to your hairline, fucking all over the place.",
    "Want someone prettier than you? Look up the town dump on the internet.",
    "If your brain was a store the owner would be broke.",
    "You always type ;help because your brain is too dumb to remember anything.",
    "Your hairline is like a peson with alzheimer's drawing a straight line.",
    "Retard in French is late, but also a great synonym for you.",
    "I can prove that God isn't real. If He was real, He would never have made something as ugly as you.",
    "You sound reasonable. It must be time to up my medication.",
    "You're so dense, light must bend around you.",
    "You're about as sharp as a bowling ball.",
    "You are proof that evolution can go in reverse.",
    "The perfect song to represent you is Nicki Minaj's 'Stupid Hoe'.",
    "Antarctica is hotter than you.",
    "What doesn't kill you disappoints me.",
    "Whats the difference between breathing in paint and talking to you? Breathing in paint kills less brain cells.",
    "You're like meat at a butcher shop. You could use a good hanging.",
    "You coffin dodging oxygen thief.",
    "You look like your mom let you have your first beer through your umbilical cord.",
    "You look like Squidward's house.",
    "It looks like you recently got set free from a block of ice.",
    "To me it seems like you enjoy being bullied at school.",
    "Damn. I'm pretty sure *both* of your fathers would be dissapointed in you.",
    "You look like you give blowjobs for library card renewals.",
    "Are you a boy or a girl? I can't tell.",
    "I wonder if you have as many Tumblr followers as you have chins.",
    "Look at yourself in the mirror. Oh - wait. You broke them all already.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're like the top piece of bread. Everybody touches you, but nobody wants you.",
    "How about you go have your one friend roast you instead.",
    "When you get an idea, a light bulb doesn't appear over your head. Instead, a pile of shit does.",
    "Is your ass jealous of the amount of shit that just came out of your mouth?",
    "I wasn't born with enough middle fingers to let you know how I feel about you.",
    "All these switches and yet you turn everyone off.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You are the best argument for post-term abortion.",
    "Everyone has the right to be stupid, but you're just abusing the privilege.",
    "You may have had sex once: with a gardening hoe.",
    "Do you realize that people just tolerate you?",
    "You're not pretty enough to be this stupid.",
    "Anyone who ever loved you was wrong.",
    "If you were anymore inbred you would be a sandwich.",
    "Now I know why everybody talks about you behind your back.",
    "I can explain it to you, but I can't understand it for you.",
    "You are one of those people who would be enormously improved by death.",
    "Your gene pool could use a little chlorine",
    "You couldn't pour water out of a boot if the instructions were on the sole.",
    "You look like a before picture.",
    "You're like the top piece of bread. Everybody touches you, but nobody wants you.",
    "I treasure the time I don't spend with you.",
    "What is that you are wearing? Looks like a dog took a shit on a knitted jumper.",
    "What's the different between you and Hitler? At least Hitler knew when to kill himself.",
    "Don't play hard to get when you're hard to want.",
    "Your bacteria is the only culture you have.",
    "The only good thing to pull itself out of your mom's vagina was your dad's dick. Too bad it wasnt fast enough.",
    "I doubt that you could drown: fat floats.",
    "Whats the difference between breathing in paint and talking to you? Breathing in paint kills less brain cells.",
    "You clearly have not been burdened by an overabundance of education.",
    "You will be utterly forgotten",
    "The best part of you ran down your mother's legs.",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "The clothes you wear are so ugly even a scarecrow wouldn't wear them.",
    "You're so ugly, when you threw a boomerang it didn't come back.",
    "You shouldn't play hide and seek, no one would look for you.",
    "Don't feel sad, don't feel blue, Frankenstein was ugly too.",
    "You're so stupid, it takes you an hour to cook minute rice.",
    "You're so dumb, your dog teaches you tricks.",
    "Don't you need a license to be that ugly?",
    "Nice shirt, what brand is it? Clearance?",
    "I was pro life. Then I met you.",
    "I just stepped in something that was smarter than you and smelled better too.",
    "I thought of you today. It reminded me to take the garbage out.",
    "You're proof that God has a sense of humor.",
    "I guess you prove that even god makes mistakes sometimes.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "What's the difference between you and eggs? Eggs get laid and you don't.",
    "Someone once said your as pretty as a picture... I agree I would love to hang you.",
    "The only reason your partner likes your dick is because they were taught to enjoy the little things in life.",
    "You were so ugly that when you were born the doctor put tinted windows on your incubator.",
    "I would burn you but burning trash is bad for the environment.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "When you were born your mom threw you out the window and the window threw you back.",
    "At least Hitler killed himself.",
    "If my dog had your face I would shave his ass and teach him to walk backwards.",
    "Your so stupid I don't have the time or the crayons to explain this to you.",
    "Calling you an idiot would be an insult to all stupid people.",
    "Some babies were dropped on their heads but you were clearly thrown at a wall.",
    "Twinkle twinkle little whore, close your legs, they're not a door.",
    "I failed a spelling test because they asked me how to spell 'bitch' and I wrote down your name.",
    "You must have been born on a highway because thats where most accidents happen.",
    "You look like the after picture of a meth ad."
  ],
  uncle_iroh: [
    "It is usually best to admit mistakes when they occur, and to seek to restore honor.",
    "It is important to draw wisdom from many different places. If you take it from only one place, it becomes rigid and stale.",
    "It's time for you to look inward and start asking yourself the big question: who are you and what do YOU want?",
    "Sharing tea with a fascinating stranger is one of life's true delights.",
    "You must never give into despair. Allow yourself to slip down that road, and you surrender to your lowest instincts. In the darkest times, hope is something you give yourself. That is the meaning of inner strength.",
    "Sometimes life is like a dark tunnel. You can’t always see the light at the end of the tunnel, but if you just keep moving you will come to a better place.",
    "Destiny is a funny thing. You never know how things are going to work out. But if you keep an open mind and an open heart, I promise you will find your own destiny.",
    "While it is always best to believe in oneself, a little help from others can be a great blessing.",
    "Pride is not the opposite of shame, but its source. True humility is the only antidote to shame.",
    "Life happens wherever you are, whether you make it or not.",
    "There is nothing wrong with letting people who love you, help you. Not that I love you. I just met you.",
    "At my age, there is really only one big surprise left, and I’d just as soon leave it a mystery.",
    "I was never angry with you. I was sad, because I was afraid you’d lost your way.",
    "Even in the material world, you will find that if you look for the light, you can often find it. But if you look for the dark, that is all you will ever see.",
    "Power in firebending comes from the breath, not the muscle!",
    "Protection and power are overrated. I think you are very wise to choose happiness and love. There are reasons each of us are born. We have to find those reasons.",
    "You are not the man you used to be. You are stronger and wiser and freer than you ever used to be. And now you have come at the crossroads of the destiny. Its time for you to choose. Its time for you to choose good.",
    "You’re looking at the rare white dragon bush. Its leaves make a tea so delicious it’s *heartbreaking!* That, or it’s the white jade bush, which is poisonous.",
    "There’s nothing wrong with a life of peace and prosperity. I suggest you think about what it is that you want from your life, and why.",
    "Sometimes the best way to solve your own problems is to help someone else.",
    "Many things that seem threatening in the dark become welcoming when we shine light on them.",
    "So I was thinking about names for my new tea shop… How about… the Jasmine Dragon? It’s dramatic, poetic… has a nice ring to it.",
    "You sound like my nephew. Always thinking you need to do things on your own without anyone's support.",
    "A man needs his rest.",
    "Happy birthday, my son. If only I could have helped you.\nLeaves from the vine\nFalling so slow\nLike fragile, tiny shells\nDrifting in the foam\nLittle soldier boy\nCome marching home\nBrave soldier boy\nComes marching home.",
    "You have light and peace inside of you. If you let it out, you can change the world around you.",
    "Are you so busy fighting you cannot see your own ship has set sail?"
  ]
}
